server:
  port: 9300
  
spring:
  application:
    name: ErickMeza-pizzeria-microservicio
  config:
    import: configserver:http://localhost:9323
  profiles:
    active: final
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
      
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka  
